package com.ybdev.permissionyb

enum class Permission
{
    CAMERA,
    READ_EXTERNAL_STORAGE,
    WRITE_EXTERNAL_STORAGE,
    READ_CALENDAR,
    WRITE_CALENDAR,
    READ_CONTACTS,
    WRITE_CONTACTS,
    RECORD_AUDIO,
    READ_SMS,
    SEND_SMS,
    ACCESS_BACKGROUND_LOCATION,
    ACCESS_COARSE_LOCATION,
    ACCESS_FINE_LOCATION
}